#:kivy 1.0.9
# ref: https://kivy.org/docs/tutorials/pong.html

<Agent>:
    size: 20, 10
    canvas:
        PushMatrix
        Rotate:
            angle: self.angle
            origin: self.center
        Rectangle:
            pos: self.pos
            size: self.size
        PopMatrix

<Ball1>:
    size: 10,10
    canvas:
        Color:
            rgba: 1,0,0,1
        Ellipse:
            pos: self.pos
            size: self.size
<Ball2>:
    size: 10,10
    canvas:
        Color:
            rgba: 0,1,1,1
        Ellipse:
            pos: self.pos
            size: self.size

<Ball3>:
    size: 10,10
    canvas:
        Color:
            rgba: 1,1,0,1
        Ellipse:
            pos: self.pos
            size: self.size
            

<Goal>:
    size: 10,10
    canvas:
        Color:
            rgba: 255, 87, 51, 1
        Ellipse:
            pos: self.pos
            size: self.size




<Game>:
    agent: game_agent
    ball1: game_ball1
    ball2: game_ball2
    ball3: game_ball3
    goal: f_goal

    Agent:
        id: game_agent
        center: self.parent.center
    Ball1:
        id: game_ball1
        center: self.parent.center
    Ball2:
        id: game_ball2
        center: self.parent.center
    Ball3:
        id: game_ball3
        center: self.parent.center
        
    Goal:
        id: f_goal
        center: self.parent.center